/**
 * Derive the neutral core manifest from the decorated classes.
 *
 * The manifest is meant to *become* the source of truth, but transcribing 24 entities and 146
 * predicates by hand is exactly the sort of task that produces a subtle, silent mistake — a wrong
 * predicate orphans data without erroring. So the first version is generated from the classes that
 * already work, and an equivalence test then holds the two in agreement.
 *
 *   node scripts/generateCoreManifest.mjs > src/generated/coreManifest.ts
 */
import { getPropertiesMetadata, getRelationsMetadata } from '@coasys/ad4m';
import { readdirSync, readFileSync } from 'node:fs';

import * as C from '../dist/classes.js';

const FILE_LANG = 'QmzSYwddqhm49PrRMzSrJf3AvmmreXMKtr1u56nbTjBFVmCzS8N';
const SCALAR = { 'xsd://string': 'string', 'xsd://integer': 'number', 'xsd://boolean': 'boolean' };

// Declared field types and defaults live in the source, not in decorator metadata: SHACL infers a
// datatype only when there is an initial value, so a `number` field that starts at 0 would
// otherwise come back as a string.
const defaults = {};
const fieldTypes = {};
for (const dir of ['src/entities', 'src/blocks']) {
  for (const file of readdirSync(dir).filter((n) => n.endsWith('.ts') && n !== 'index.ts')) {
    const src = readFileSync(`${dir}/${file}`, 'utf8');
    const cls = file.replace('.ts', '');
    defaults[cls] = {};
    fieldTypes[cls] = {};
    // Any declared type, not just the three scalars: a field may be typed as a union
    // (`mode: SignalMode = 'toggle'`) or nullable (`css: string | null = null`), and those carry
    // defaults that matter just as much. The scalar is read out of the type text where it is
    // stated, and left to SHACL's inference where it isn't.
    for (const m of src.matchAll(/^ {2}(\w+)!?: ([^=;]+?) = ([^;]+);/gm)) {
      const [, prop, typeText, rawValue] = m;
      const declared = typeText.trim();
      if (!declared.endsWith('[]')) {
        const scalar = /\bnumber\b/.test(declared)
          ? 'number'
          : /\bboolean\b/.test(declared)
            ? 'boolean'
            : /\bstring\b/.test(declared)
              ? 'string'
              : undefined;
        if (scalar) fieldTypes[cls][prop] = scalar;
      }
      const raw = rawValue.trim();
      if (raw === '[]') continue;
      defaults[cls][prop] =
        raw === 'null'
          ? null
          : raw.startsWith("'")
            ? raw.slice(1, -1)
            : raw === 'true' || raw === 'false'
              ? raw === 'true'
              : Number(raw);
    }
  }
}

const names = Object.keys(C).filter((k) => typeof C[k] === 'function' && C[k].generateSHACL);
const entities = {};

for (const name of names) {
  const shape = C[name].generateSHACL().shape;
  if (!shape) continue;
  const relationMeta = getRelationsMetadata(C[name]);
  const propertyMeta = getPropertiesMetadata(C[name]);
  const entity = { properties: {}, relations: {} };

  for (const p of shape.properties ?? []) {
    if (!p.name) continue;
    if (p.hasValue !== undefined) {
      entity.flag = { predicate: p.path, value: p.hasValue };
      continue;
    }
    if (relationMeta[p.name]) {
      const target = p.class
        ? p.class
            .split(/[#/]/)
            .pop()
            .replace(/Shape$/, '')
        : '';
      entity.relations[p.name] = {
        target: names.includes(target) ? target : '',
        cardinality: p.maxCount === 1 ? 'one' : 'many',
        predicate: p.path,
      };
      continue;
    }
    const spec = { type: fieldTypes[name]?.[p.name] ?? SCALAR[p.datatype] ?? 'string', predicate: p.path };
    if ((p.minCount ?? 0) >= 1) spec.required = true;
    if (p.resolveLanguage === FILE_LANG) {
      spec.format = 'file';
      if (p.transform) spec.readAs = 'dataUri';
    }
    const initial = propertyMeta[p.name]?.initial;
    const fallback = initial && !String(initial).includes('uninitialized') ? initial : undefined;
    const value = defaults[name]?.[p.name] !== undefined ? defaults[name][p.name] : fallback;
    if (value !== undefined) spec.default = value;
    entity.properties[p.name] = spec;
  }
  // No type marker in the shape means nothing is ever stored *as* this — it is a base others
  // extend, and the compiler must not mint a marker for it.
  if (!entity.flag) entity.abstract = true;
  entities[name] = entity;
}

const body = JSON.stringify({ version: '1', entities }, null, 2);
process.stdout.write(`/**
 * WE's core vocabulary, declared.
 *
 * GENERATED by scripts/generateCoreManifest.mjs from the decorated classes — do not edit by hand
 * while those remain the source. \`coreManifest.test.ts\` asserts the two still agree, so a change
 * to either without the other fails rather than drifting.
 */
import type { ModelManifest } from '@we/backend-shared';

export const CORE_MANIFEST: ModelManifest = ${body} as ModelManifest;
`);
