packages:
  - apps/*
  - apps/playgrounds/*/*
  - packages/*
  - packages/design-system/*
  - packages/schema-system/*
  - packages/block-system/*
  - packages/utils/*

ignoredBuiltDependencies:
  - electron
