/**
 * Build-time generate script.
 *
 * 1. Assembles the full context reference
 * 2. Writes instruction files (for local AI agents)
 * 3. Generates schemaContext.ts (for in-app AI)
 *
 * Run via: node --import tsx packages/ai-context/src/generate.ts
 * Or via: pnpm --filter @we/ai-context generate-context
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { assembleReference } from './assembler.js';
import { extractPrimitives } from './extractors/cem.js';
import { extractModels } from './extractors/models.js';
import { extractTokens } from './extractors/tokens.js';
import { extractComponents } from './extractors/typescript.js';
import { designSystemProps } from './fragments/design-system-props.js';
import { routing } from './fragments/routing.js';
import { rules } from './fragments/rules.js';
import { schemaOperators } from './fragments/schema-operators.js';
import { storePatterns } from './fragments/store-patterns.js';
import { stores } from './fragments/stores.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
// From src/generate.ts: up to ai-context/, up to packages/, up to repo root
const packageRoot = resolve(__dirname, '..');
const repoRoot = resolve(packageRoot, '../..');

function main() {
  console.log('Generating AI context...');

  // Resolve all paths explicitly (tsup bundles all extractors into dist/generate.js,
  // so their default __dirname-relative paths would be wrong)
  const designSystemRoot = resolve(repoRoot, 'packages/design-system');

  const context = {
    primitives: extractPrimitives(resolve(designSystemRoot, '3-primitives/custom-elements.json')),
    components: extractComponents({
      components: resolve(designSystemRoot, '4-components/src'),
      widgets: resolve(designSystemRoot, '5-widgets/src'),
    }),
    tokens: extractTokens(resolve(designSystemRoot, '1-tokens/src')),
    models: extractModels(resolve(repoRoot, 'packages/models/src')),
    fragments: { schemaOperators, designSystemProps, routing, stores, storePatterns, rules },
  };

  const reference = assembleReference(context);

  // 1. Write instruction file for GitHub Copilot
  const instructionContent = wrapWithFraming(reference);
  const copilotPath = resolve(repoRoot, '.github/copilot-instructions.md');
  mkdirSync(dirname(copilotPath), { recursive: true });
  writeFileSync(copilotPath, instructionContent, 'utf-8');
  console.log(`  Written: ${copilotPath}`);

  // 2. Write CLAUDE.md for Claude Code (terminal agent)
  const claudePath = resolve(repoRoot, 'CLAUDE.md');
  writeFileSync(claudePath, instructionContent, 'utf-8');
  console.log(`  Written: ${claudePath}`);

  // 3. Write Cursor rules file
  const cursorDir = resolve(repoRoot, '.cursor/rules');
  mkdirSync(cursorDir, { recursive: true });
  writeFileSync(resolve(cursorDir, 'we-schema.mdc'), instructionContent, 'utf-8');
  console.log(`  Written: ${resolve(cursorDir, 'we-schema.mdc')}`);

  // 4. Generate schemaContext.ts (runtime constant for in-app AI)
  const schemaContextPath = resolve(packageRoot, 'src/schemaContext.ts');
  const schemaContextContent = [
    '// AUTO-GENERATED by packages/ai-context/src/generate.ts',
    '// Do not edit manually. Run: pnpm --filter @we/ai-context generate-context',
    '',
    `export const schemaContext = ${JSON.stringify(reference)};`,
    '',
  ].join('\n');
  writeFileSync(schemaContextPath, schemaContextContent, 'utf-8');
  console.log(`  Written: ${schemaContextPath}`);

  console.log('Done.');
}

function wrapWithFraming(reference: string): string {
  return `# WE Schema Reference

This file is auto-generated by \`@we/ai-context\`. Do not edit manually.
Regenerate with: \`pnpm --filter @we/ai-context generate-context\`

Use this reference when generating or updating WE UI schemas.
All schemas must be valid JSON. Only use components, props, tokens, and patterns documented below.

---

${reference}
`;
}

main();
