/**
 * Template Section Indexer
 *
 * Computes a section index by tree-walking a TemplateSchema.
 * The index is stored alongside the schema in the blob, ensuring
 * all clients (and shared copies) use identical section keys.
 *
 * The indexer runs at specific points:
 * - Template creation → generate initial index
 * - After structural edits (add/remove/move children) → re-index
 * - On share → index travels with the blob → recipient gets identical keys
 *
 * Targeted section edits (changing props within a section) do NOT
 * require re-indexing — the tree structure is unchanged.
 *
 * Section types:
 * - "route"      — nodes inside a $routes array (keyed by path)
 * - "navigation" — landmark components like CollapsibleSidebar (keyed by side prop)
 * - "panel"      — large child subtrees within a route (keyed by qualifier)
 */

import type { OperatorToken, RouteSchema, SchemaNode, TemplateSchema } from './types';

/** Type guard: a child is a SchemaNode (not a string or operator token) */
function isSchemaChild(child: string | SchemaNode | OperatorToken): child is SchemaNode {
  if (typeof child !== 'object' || child === null) return false;
  // A node with `type` or `id` is always a SchemaNode, even if it also
  // carries $-prefixed properties like $localState.
  if ('type' in child || 'id' in child) return true;
  // Otherwise reject objects whose keys are all $-prefixed (operator tokens).
  return !Object.keys(child).some((k) => k.startsWith('$'));
}

/**
 * Call fn for each SchemaNode-shaped value directly embedded in node.props.
 * Handles plain SchemaNode values (e.g. $if.props.then) and arrays of nodes.
 * Does NOT recurse into non-SchemaNode objects to avoid walking operator tokens.
 */
function forEachPropsNode(node: SchemaNode, fn: (child: SchemaNode) => void): void {
  if (!node.props) return;
  for (const val of Object.values(node.props)) {
    if (typeof val !== 'object' || val === null) continue;
    if (Array.isArray(val)) {
      for (const item of val) {
        if (isSchemaChild(item as SchemaNode)) fn(item as SchemaNode);
      }
    } else if (isSchemaChild(val as SchemaNode)) {
      fn(val as SchemaNode);
    }
  }
}

/** A navigable region in the template tree */
export interface SectionEntry {
  /** Human-readable key, e.g. "route:/", "navigation:left", "panel:/:stats-cards" */
  key: string;
  /** Section classification */
  type: 'route' | 'navigation' | 'panel' | 'root';
  /** Tree path for extraction — array of child indices from root */
  path: number[];
  /** Estimated serialized JSON size in characters */
  sizeEstimate: number;
}

/**
 * The stored template blob format.
 * Contains both the schema tree and the pre-computed section index.
 */
export interface StoredTemplate {
  /** The full template schema tree */
  schema: TemplateSchema;
  /** Pre-computed section index — generated by computeSectionIndex, stored alongside */
  sections: SectionEntry[];
}

/**
 * Ensure a template blob has a section index.
 * If sections are missing (legacy template, manual JSON import), computes them.
 * If present, returns as-is.
 */
export function ensureSections(blob: StoredTemplate | TemplateSchema): StoredTemplate {
  if ('sections' in blob && 'schema' in blob && Array.isArray(blob.sections)) {
    return blob as StoredTemplate;
  }
  // Legacy format — just a raw TemplateSchema
  const schema = blob as TemplateSchema;
  return { schema, sections: computeSectionIndex(schema) };
}

/** Landmark component types that are indexed as navigation sections */
const NAVIGATION_TYPES = new Set(['CollapsibleSidebar']);

/** Approximate size threshold (in serialized chars) above which a subtree gets sub-indexed as panels */
const PANEL_THRESHOLD = 4000; // ~200 lines of JSON ≈ 4000 chars

/** Estimate the serialized size of a node */
function estimateSize(node: SchemaNode | string): number {
  return JSON.stringify(node).length;
}

/** Infer a qualifier for a panel section from the node's structure */
function inferQualifier(node: SchemaNode, index: number): string {
  // Prefer a distinguishing prop: component type
  if (node.type) {
    // Convert PascalCase to kebab-case
    const kebab = node.type.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
    return kebab;
  }
  // Fallback to index
  return `child-${index}`;
}

/**
 * Compute a section index for a template schema.
 * Returns a flat list of SectionEntry objects identifying the navigable regions.
 */
export function computeSectionIndex(schema: SchemaNode): SectionEntry[] {
  const sections: SectionEntry[] = [];

  // Root section
  sections.push({
    key: 'root',
    type: 'root',
    path: [],
    sizeEstimate: estimateSize(schema),
  });

  // Walk top-level children for navigation landmarks
  if (schema.children) {
    for (let i = 0; i < schema.children.length; i++) {
      const child = schema.children[i];
      if (!isSchemaChild(child)) continue;

      if (child.type && NAVIGATION_TYPES.has(child.type)) {
        const side = (child.props?.side as string) || `nav-${i}`;
        sections.push({
          key: `navigation:${side}`,
          type: 'navigation',
          path: [i],
          sizeEstimate: estimateSize(child),
        });
      }
    }
  }

  // Find and index routes at any depth
  indexRoutes(schema, [], sections);

  return sections;
}

/** Recursively find $routes arrays and index each route */
function indexRoutes(node: SchemaNode, currentPath: number[], sections: SectionEntry[]): void {
  // Check this node's routes
  if (node.routes && node.routes.length > 0) {
    for (let i = 0; i < node.routes.length; i++) {
      const route = node.routes[i] as RouteSchema;
      const routePath = [...currentPath, -1, i]; // -1 signals "routes" array vs "children"
      const routeKey = `route:${route.path}`;
      const size = estimateSize(route);

      sections.push({
        key: routeKey,
        type: 'route',
        path: routePath,
        sizeEstimate: size,
      });

      // Sub-index large routes into panels
      if (size > PANEL_THRESHOLD) {
        indexPanels(route, routePath, route.path, sections);
      }
    }
  }

  // Recurse into children
  if (node.children) {
    for (let i = 0; i < node.children.length; i++) {
      const child = node.children[i];
      if (isSchemaChild(child)) {
        indexRoutes(child, [...currentPath, i], sections);
      }
    }
  }
}

/**
 * Index large children of a route (or nested container) as panel sections.
 * Recurses through single-child wrappers to find meaningful split points.
 */
function indexPanels(node: SchemaNode, nodePath: number[], routePath: string, sections: SectionEntry[]): void {
  const children = node.children;
  if (!children || children.length === 0) return;

  // Filter to SchemaNode children (skip strings)
  const nodeChildren: { node: SchemaNode; index: number }[] = [];
  for (let i = 0; i < children.length; i++) {
    const child = children[i];
    if (isSchemaChild(child)) {
      nodeChildren.push({ node: child, index: i });
    }
  }

  // Single child — skip wrapper, recurse into it
  if (nodeChildren.length === 1) {
    const only = nodeChildren[0];
    indexPanels(only.node, [...nodePath, only.index], routePath, sections);
    return;
  }

  // Multiple children — index those exceeding or near the threshold
  const usedQualifiers = new Set<string>();
  for (const { node: child, index } of nodeChildren) {
    const size = estimateSize(child);
    if (size < PANEL_THRESHOLD / 4) continue; // Skip tiny children (< ~50 lines)

    let qualifier = inferQualifier(child, index);
    // Deduplicate qualifiers within the same route
    if (usedQualifiers.has(qualifier)) {
      qualifier = `${qualifier}-${index}`;
    }
    usedQualifiers.add(qualifier);

    const panelPath = [...nodePath, index];
    sections.push({
      key: `panel:${routePath}:${qualifier}`,
      type: 'panel',
      path: panelPath,
      sizeEstimate: size,
    });

    // Recurse into large panels
    if (size > PANEL_THRESHOLD) {
      indexPanels(child, panelPath, routePath, sections);
    }
  }
}

/**
 * Extract a subtree from a schema by path.
 * Returns the node at the given path, or null if the path is invalid.
 */
export function extractByPath(schema: SchemaNode, path: number[]): SchemaNode | null {
  let current: SchemaNode = schema;

  for (let i = 0; i < path.length; i++) {
    const idx = path[i];

    if (idx === -1) {
      // Next index is into routes array
      const routeIdx = path[++i];
      if (!current.routes || routeIdx >= current.routes.length) return null;
      current = current.routes[routeIdx] as SchemaNode;
    } else {
      // Index into children array
      if (!current.children || idx >= current.children.length) return null;
      const child = current.children[idx];
      if (!isSchemaChild(child)) return null;
      current = child;
    }
  }

  return current;
}

// ── Node ID Patching Utilities ─────────────────────────────────────

/** Result of finding a node by ID in the tree */
export type FindNodeResult = {
  node: SchemaNode;
  parent: SchemaNode | null;
  key: string; // 'children' | 'routes' | 'slots.<name>'
  index: number;
};

/**
 * Assign stable IDs to every node in the tree that lacks one.
 * Deduplicates: if two nodes share the same ID, the second gets a new one.
 * Mutates the schema in place and returns it.
 */
export function ensureNodeIds(schema: SchemaNode): SchemaNode {
  // First pass: collect all existing IDs and find max numeric suffix
  const existingIds = new Set<string>();
  let maxSuffix = 0;

  function collectIds(node: SchemaNode): void {
    if (node.id) {
      const m = /^n(\d+)$/.exec(node.id);
      if (m) maxSuffix = Math.max(maxSuffix, parseInt(m[1], 10));
    }
    if (node.children) {
      for (const child of node.children) {
        if (isSchemaChild(child)) collectIds(child);
      }
    }
    if (node.routes) {
      for (const route of node.routes) collectIds(route as SchemaNode);
    }
    if (node.slots) {
      for (const slotNode of Object.values(node.slots)) collectIds(slotNode);
    }
    forEachPropsNode(node, collectIds);
  }
  collectIds(schema);

  // Second pass: assign/deduplicate IDs
  let counter = maxSuffix + 1;

  function assignIds(node: SchemaNode): void {
    if (!node.id) {
      node.id = `n${counter++}`;
    } else if (existingIds.has(node.id)) {
      // Duplicate — reassign
      node.id = `n${counter++}`;
    }
    existingIds.add(node.id);

    if (node.children) {
      for (const child of node.children) {
        if (isSchemaChild(child)) assignIds(child);
      }
    }
    if (node.routes) {
      for (const route of node.routes) assignIds(route as SchemaNode);
    }
    if (node.slots) {
      for (const slotNode of Object.values(node.slots)) assignIds(slotNode);
    }
    forEachPropsNode(node, assignIds);
  }
  assignIds(schema);

  return schema;
}

/**
 * Find a node by its ID in the tree.
 * Returns the node, its parent, which array key it lives in, and its index.
 * Returns null if the ID is not found or is empty string.
 */
export function findNodeById(schema: SchemaNode, targetId: string): FindNodeResult | null {
  if (!targetId) return null;

  function search(node: SchemaNode, parent: SchemaNode | null, key: string, index: number): FindNodeResult | null {
    if (node.id === targetId) return { node, parent, key, index };

    if (node.children) {
      for (let i = 0; i < node.children.length; i++) {
        const child = node.children[i];
        if (isSchemaChild(child)) {
          const result = search(child, node, 'children', i);
          if (result) return result;
        }
      }
    }
    if (node.routes) {
      for (let i = 0; i < node.routes.length; i++) {
        const result = search(node.routes[i] as SchemaNode, node, 'routes', i);
        if (result) return result;
      }
    }
    if (node.slots) {
      for (const [slotName, slotNode] of Object.entries(node.slots)) {
        const result = search(slotNode, node, `slots.${slotName}`, 0);
        if (result) return result;
      }
    }
    if (node.props) {
      for (const [propName, val] of Object.entries(node.props)) {
        if (typeof val !== 'object' || val === null) continue;
        if (Array.isArray(val)) {
          for (let i = 0; i < val.length; i++) {
            if (isSchemaChild(val[i] as SchemaNode)) {
              const result = search(val[i] as SchemaNode, node, `props.${propName}`, i);
              if (result) return result;
            }
          }
        } else if (isSchemaChild(val as SchemaNode)) {
          const result = search(val as SchemaNode, node, `props.${propName}`, 0);
          if (result) return result;
        }
      }
    }
    return null;
  }

  return search(schema, null, 'root', 0);
}

/**
 * Merge a partial node into an existing node using JSON Merge Patch semantics.
 * - Keys present in patch override existing
 * - Keys absent from patch are preserved
 * - Keys set to null are deleted
 * - Nested plain objects (e.g. props) are shallow-merged
 * - Arrays (e.g. children, routes) replace entirely
 * - The `id` field is always preserved from the existing node
 */
export function mergeNode(existing: SchemaNode, patch: Record<string, unknown>): SchemaNode {
  // When the node type changes, old type-specific keys (props, children, slots, etc.) are stale.
  // Replace them wholesale instead of shallow-merging to avoid leaking invalid props.
  const typeChanging = 'type' in patch && patch.type !== existing.type;

  const result = { ...existing };

  for (const [key, value] of Object.entries(patch)) {
    // Never allow overwriting id
    if (key === 'id') continue;

    if (value === null) {
      // null = delete
      delete (result as Record<string, unknown>)[key];
    } else if (Array.isArray(value) || typeof value !== 'object' || value === undefined) {
      // Primitives, arrays, undefined — replace directly
      (result as Record<string, unknown>)[key] = value;
    } else {
      // Plain object — check if existing is also a plain object for shallow merge
      const existingVal = (existing as Record<string, unknown>)[key];
      if (!typeChanging && existingVal && typeof existingVal === 'object' && !Array.isArray(existingVal)) {
        // Shallow merge (only when type stays the same)
        const merged = { ...(existingVal as Record<string, unknown>) };
        for (const [subKey, subVal] of Object.entries(value as Record<string, unknown>)) {
          if (subVal === null) {
            delete merged[subKey];
          } else {
            merged[subKey] = subVal;
          }
        }
        (result as Record<string, unknown>)[key] = merged;
      } else {
        // Type changed or no existing object to merge into — just assign
        (result as Record<string, unknown>)[key] = value;
      }
    }
  }

  // When changing type, remove keys from the old node that the patch doesn't mention
  // (e.g. old props, children, slots that don't belong to the new type)
  if (typeChanging) {
    const preserve = new Set(['id', 'type', ...Object.keys(patch)]);
    for (const key of Object.keys(result)) {
      if (!preserve.has(key)) {
        delete (result as Record<string, unknown>)[key];
      }
    }
  }

  return result;
}

/** Error result from insert/remove operations */
export type PatchError = { error: string };

/**
 * Insert a child node into a parent's children or routes array.
 * Mutates the cloned schema. Returns error string on failure, undefined on success.
 */
export function insertChild(
  schema: SchemaNode,
  parentId: string,
  arrayKey: 'children' | 'routes',
  node: SchemaNode,
  position?: { after: string } | { before: string },
): PatchError | undefined {
  // Find the parent
  let parent: SchemaNode;
  if (parentId === '') {
    parent = schema;
  } else {
    const found = findNodeById(schema, parentId);
    if (!found) return { error: `No node with id "${parentId}" found in the current schema.` };
    parent = found.node;
  }

  // Ensure the array exists
  if (!parent[arrayKey]) {
    (parent as Record<string, unknown>)[arrayKey] = [];
  }
  const arr = parent[arrayKey] as SchemaNode[];

  if (!position) {
    // Append
    arr.push(node);
  } else if ('after' in position) {
    const sibIdx = arr.findIndex((c) => (c as SchemaNode).id === position.after);
    if (sibIdx === -1)
      return { error: `Sibling id "${position.after}" not found in ${arrayKey} of node "${parentId}".` };
    arr.splice(sibIdx + 1, 0, node);
  } else {
    const sibIdx = arr.findIndex((c) => (c as SchemaNode).id === position.before);
    if (sibIdx === -1)
      return { error: `Sibling id "${position.before}" not found in ${arrayKey} of node "${parentId}".` };
    arr.splice(sibIdx, 0, node);
  }

  return undefined;
}

/**
 * Remove a child node from a parent's children or routes array by child ID.
 * Mutates the cloned schema. Returns error string on failure, undefined on success.
 */
export function removeChild(
  schema: SchemaNode,
  parentId: string,
  arrayKey: 'children' | 'routes',
  childId: string,
): PatchError | undefined {
  // Find the parent
  let parent: SchemaNode;
  if (parentId === '') {
    parent = schema;
  } else {
    const found = findNodeById(schema, parentId);
    if (!found) return { error: `No node with id "${parentId}" found in the current schema.` };
    parent = found.node;
  }

  const arr = parent[arrayKey] as SchemaNode[] | undefined;
  if (!arr) return { error: `Node "${parentId}" has no ${arrayKey} array.` };

  const idx = arr.findIndex((c) => (c as SchemaNode).id === childId);
  if (idx === -1) return { error: `Child id "${childId}" not found in ${arrayKey} of node "${parentId}".` };

  arr.splice(idx, 1);
  return undefined;
}

// ── Legacy path-based patching (deprecated — kept for backward compat) ──

/**
 * Validate that each patch's path is reachable in the current schema
 * and that each replacement node has a 'type' field.
 * @deprecated Use ID-based patching (findNodeById + mergeNode) instead.
 */
export function validatePatches(
  patches: Array<{ path: number[]; node: unknown }>,
  schema: SchemaNode,
): { valid: true } | { valid: false; error: string } {
  for (const { path, node } of patches) {
    // Validate all path elements are integers
    for (let j = 0; j < path.length; j++) {
      if (typeof path[j] !== 'number' || !Number.isInteger(path[j])) {
        return {
          valid: false,
          error: `Path [${path.join(', ')}] invalid: element at index ${j} is "${path[j]}" — path must contain only integers, not strings like "children" or "routes"`,
        };
      }
    }

    let target: SchemaNode = schema;
    for (let i = 0; i < path.length; i++) {
      if (path[i] === -1) {
        const routes = target.routes;
        const routeIdx = path[i + 1];
        if (routeIdx === undefined) {
          return { valid: false, error: `Path [${path.join(', ')}] invalid: -1 at end with no route index` };
        }
        if (!routes || routeIdx < 0 || routeIdx >= routes.length) {
          return {
            valid: false,
            error: `Path [${path.join(', ')}] invalid: route index ${routeIdx} out of bounds (node has ${routes?.length ?? 0} routes)`,
          };
        }
        target = routes[routeIdx] as SchemaNode;
        i++;
        continue;
      }

      const children = target.children;
      if (!children || path[i] < 0 || path[i] >= children.length) {
        return {
          valid: false,
          error: `Path [${path.join(', ')}] invalid: index ${path[i]} out of bounds at depth ${i} (node has ${children?.length ?? 0} children)`,
        };
      }
      const child = children[path[i]];
      if (typeof child === 'string' || child === null || child === undefined) {
        return {
          valid: false,
          error: `Path [${path.join(', ')}] invalid: node at depth ${i} is a text node, not a SchemaNode`,
        };
      }
      target = child as SchemaNode;
    }

    if (!node || typeof node !== 'object' || !('type' in node)) {
      return { valid: false, error: `Patch at [${path.join(', ')}]: node must have a 'type' field` };
    }
  }
  return { valid: true };
}

/**
 * Patch a subtree into a schema at the given path.
 * Returns a new schema with the subtree replaced (does not mutate the original).
 * @deprecated Use ID-based patching (findNodeById + mergeNode + insertChild + removeChild) instead.
 */
export function patchByPath(schema: SchemaNode, path: number[], replacement: SchemaNode): SchemaNode {
  if (path.length === 0) return replacement;

  const clone = structuredClone(schema);

  // Parse raw path into segments: each segment is either a children index or a route index
  const segments: { isRoute: boolean; index: number }[] = [];
  for (let i = 0; i < path.length; i++) {
    if (path[i] === -1) {
      segments.push({ isRoute: true, index: path[++i] });
    } else {
      segments.push({ isRoute: false, index: path[i] });
    }
  }

  // Navigate to the parent of the target (all segments except last)
  let parent: SchemaNode = clone;
  for (let i = 0; i < segments.length - 1; i++) {
    const seg = segments[i];
    if (seg.isRoute) {
      if (!parent.routes || seg.index >= parent.routes.length) {
        throw new Error(`Invalid path: routes[${seg.index}] does not exist`);
      }
      parent = parent.routes[seg.index] as SchemaNode;
    } else {
      if (!parent.children || seg.index >= parent.children.length) {
        throw new Error(`Invalid path: children[${seg.index}] does not exist`);
      }
      const child = parent.children[seg.index];
      if (!isSchemaChild(child)) {
        throw new Error(`Invalid path: children[${seg.index}] is not a schema node`);
      }
      parent = child;
    }
  }

  // Apply the last segment
  const last = segments[segments.length - 1];
  if (last.isRoute) {
    if (!parent.routes || last.index >= parent.routes.length) {
      throw new Error(`Invalid path: routes[${last.index}] does not exist`);
    }
    parent.routes[last.index] = replacement as RouteSchema;
  } else {
    if (!parent.children || last.index >= parent.children.length) {
      throw new Error(`Invalid path: children[${last.index}] does not exist`);
    }
    parent.children[last.index] = replacement;
  }

  return clone;
}
