import { fileToDataUri, Flag, HasOne, Model, Property } from '@coasys/ad4m';

import { LocationBlock } from '../blocks/LocationBlock';
import { FILE_STORAGE_LANGUAGE } from '../constants';
import { WeNode } from '../WeNode';

@Model({ name: 'AgentProfile' })
export class AgentProfile extends WeNode {
  @Flag({ through: 'we://flag', value: 'we://agent_profile' })
  flag: string = '';

  @Property({ through: 'we://first_name' })
  firstName: string = '';

  @Property({ through: 'we://last_name' })
  lastName: string = '';

  @Property({ through: 'we://handle' })
  handle: string = '';

  @Property({ through: 'we://bio' })
  bio: string = '';

  @HasOne(() => LocationBlock, { through: 'we://location' })
  location?: LocationBlock;

  @Property({ through: 'we://profile_image', resolveLanguage: FILE_STORAGE_LANGUAGE, transform: fileToDataUri })
  avatar?: string;

  @Property({ through: 'we://cover_image', resolveLanguage: FILE_STORAGE_LANGUAGE, transform: fileToDataUri })
  coverImage?: string;
}

export interface AgentProfile {
  /** Generated by @HasOne — links a new LocationBlock as this agent's location. */
  setLocation(loc: LocationBlock): Promise<void>;
}
