import { fileToDataUri, Flag, HasOne, Model, Property } from '@coasys/ad4m';

import { LocationBlock } from '../blocks/LocationBlock';
import { FILE_STORAGE_LANGUAGE } from '../constants';
import { WeNode } from '../WeNode';

@Model({ name: 'Space' })
export class Space extends WeNode {
  @Flag({ through: 'we://flag', value: 'we://space' })
  flag: string = '';

  @Property({ through: 'we://uuid' })
  uuid: string = '';

  @Property({ through: 'we://url' })
  url?: string;

  @Property({ through: 'we://name', required: true })
  name: string = '';

  @Property({ through: 'we://description', required: true })
  description: string = '';

  @Property({ through: 'we://discovery' })
  discovery: string = 'hidden';

  @Property({ through: 'we://image', resolveLanguage: FILE_STORAGE_LANGUAGE, transform: fileToDataUri })
  avatar?: string;

  @Property({ through: 'we://thumbnail', resolveLanguage: FILE_STORAGE_LANGUAGE, transform: fileToDataUri })
  coverImage?: string;

  @Property({ through: 'we://default_template_id' })
  defaultTemplateId: string = '';

  @Property({ through: 'we://default_theme_id' })
  defaultThemeId: string = '';

  /**
   * Which feature modules this community has turned on, as a JSON array of module ids.
   *
   * **Empty means "not decided", not "none".** A space created before this field existed, or by an
   * agent who never opened the setting, must keep rendering the chrome it always had — so an unset
   * value falls back to the modules the deployment's seed activated. Treating empty as "none" would
   * silently strip existing spaces of every module the moment this shipped.
   *
   * A JSON string rather than a relation because the values are ids from the seed, not entities in
   * the perspective — the same shape `AgentSettings.datasetOrder` uses for an ordered id list.
   */
  @Property({ through: 'we://enabled_modules' })
  enabledModules: string = '';

  @HasOne(() => LocationBlock, { through: 'we://location' })
  location?: LocationBlock;
}

export interface Space {
  /** Generated by @HasOne — links a new LocationBlock as this space's location. */
  setLocation(loc: LocationBlock): Promise<void>;
}
