import { fileToDataUri, Flag, HasOne, Model, Property } from '@coasys/ad4m';

import { LocationBlock } from '../blocks/LocationBlock';
import { FILE_STORAGE_LANGUAGE } from '../constants';
import { WeNode } from '../WeNode';

@Model({ name: 'Space' })
export class Space extends WeNode {
  @Flag({ through: 'we://flag', value: 'we://space' })
  flag: string = '';

  @Property({ through: 'we://uuid' })
  uuid: string = '';

  @Property({ through: 'we://url' })
  url?: string;

  @Property({ through: 'we://name', required: true })
  name: string = '';

  @Property({ through: 'we://description', required: true })
  description: string = '';

  @Property({ through: 'we://visibility' })
  visibility: string = '';

  @Property({
    through: 'we://image',
    resolveLanguage: FILE_STORAGE_LANGUAGE,
    transform: fileToDataUri,
  })
  avatar?: string;

  @Property({
    through: 'we://thumbnail',
    resolveLanguage: FILE_STORAGE_LANGUAGE,
    transform: fileToDataUri,
  })
  coverImage?: string;

  @HasOne(() => LocationBlock, { through: 'we://location' })
  location?: LocationBlock;
}

export interface Space {
  /** Generated by @HasOne — links a new LocationBlock as this space's location. */
  setLocation(loc: LocationBlock): Promise<void>;
}
