import './primitives/avatar';
import './primitives/badge';
import './primitives/button';
import './primitives/card';
import './primitives/checkbox';
import './primitives/form-field';
import './primitives/grid';
import './primitives/icon';
import './primitives/iframe';
import './primitives/image';
import './primitives/input';
import './primitives/menu';
import './primitives/menu-group';
import './primitives/menu-item';
import './primitives/modal';
import './primitives/popover';
import './primitives/radio';
import './primitives/select';
import './primitives/spinner';
import './primitives/text';
import './primitives/textarea';
import './primitives/tooltip';
import './primitives/tab';
import './primitives/tabs';

export { setIconResolver } from './primitives/icon';
