/**
 * Developer patterns fragment.
 *
 * This content is included in IDE instruction files (copilot-instructions.md,
 * CLAUDE.md, cursor rules) but intentionally EXCLUDED from the in-app AI context
 * (schemaContext.ts) because it is irrelevant when an AI is editing JSON templates.
 *
 * Add patterns here that help IDEs / terminal agents working directly in the
 * TypeScript codebase (stores, services, tests, scripts).
 */

export const devPatterns = `
## Developer Patterns (codebase work — not for JSON schema authoring)

---

### Using the Design System in TypeScript Components

When writing Solid TSX components (stores, editor panels, settings UI, etc.), always
reach for design system primitives before writing raw HTML elements with inline styles.

**Layout:** Use \`Column\`, \`Row\`, and \`Grid\` from \`@we/components/solid\` for all
flex and grid layouts. DS props (\`gap\`, \`p\`, \`px\`, \`bg\`, \`r\`, \`border\`, etc.)
cover the vast majority of layout needs without inline styles.
- \`Grid\` supports uniform columns (\`columns={3}\`), responsive auto-fill
  (\`minChildWidth="280px"\`), and custom templates (\`template="28px 1fr 28px"\`).
- Use the \`styles\` prop only for CSS that genuinely has no DS equivalent.

**Text:** Use \`we-text\` with its own props (\`fontSize\`, \`fontWeight\`, \`color\`,
\`truncate\`, \`variant\`, etc.) rather than passing everything through \`style={{}}\`.

**Interactive controls:** Use \`we-button\`, \`we-input\`, \`we-checkbox\`, \`we-select\`,
\`we-switch\` etc. — they bring theming, focus rings, hover states, and accessibility
for free. Never roll custom \`<button>\` or \`<input>\` elements when a primitive fits.

**Scrollable areas:** Use \`we-scroll-area\` instead of \`overflow: auto\` on a div —
it gives consistently styled scrollbars across themes.

**Dividers:** Use \`we-divider\` or the \`borderBottom\`/\`borderTop\` DS prop on a
\`Column\`/\`Row\` rather than a raw \`<hr>\` or border on a wrapper div.

**Token values:** Use \`tokenVar\` from \`@we/design-utils\` when you need a token value
inside a \`style={{}}\` object. Prefer DS props directly where possible.

Raw inline styles and hardcoded CSS variable strings (\`var(--we-color-neutral-400)\`)
are a signal that a DS prop or primitive is being missed — check before reaching for
\`style={{}}\`.

---

### Auto-generated Files — Never Edit Directly

The following files are fully regenerated by \`pnpm --filter @we/ai-context generate-context\`.
**Never edit them manually** — changes will be overwritten on the next generation run.

| File | Source to edit instead |
|---|---|
| \`CLAUDE.md\` | \`packages/ai-context/src/fragments/\` |
| \`.github/copilot-instructions.md\` | \`packages/ai-context/src/fragments/\` |
| \`.cursor/rules/we-schema.mdc\` | \`packages/ai-context/src/fragments/\` |
| \`packages/ai-context/src/schemaContext.ts\` | \`packages/ai-context/src/fragments/\` or \`assembler.ts\` |
| \`packages/ai-context/src/contextData.ts\` | \`packages/ai-context/src/generate.ts\` or \`storeEntries\` |

To add or change documented schema fields, tokens, conventions, or rules:
1. Edit the appropriate fragment in \`packages/ai-context/src/fragments/\`
2. Run \`pnpm --filter @we/ai-context generate-context\` to regenerate all output files
3. Commit both the fragment source change and the regenerated files together

---

### Git Workflow — Default Branch & PR Summaries

\`main\` is the production branch — it only receives periodic merges for releases.
\`dev\` is where all active work happens. Always branch from \`dev\`, and always
diff/compare against \`dev\` (e.g. \`git diff dev...HEAD\`, \`git log dev..HEAD\`) —
never \`main\`, even though it exists.

**PR summary convention:** when asked to write a PR summary document for a branch,
create a new \`PR_<DESCRIPTIVE_NAME>.md\` file at the repo root (e.g.
\`PR_COLLECTION_BLOCK_TEXT_CONTENT.md\`), based on \`git diff dev...<branch>\` and the
branch's commit log, with these sections:

- **Summary** — the problem being solved and the high-level approach, 1–2 paragraphs.
- **Changes** — one entry per file or logical group, explaining *why* the change was
  made, not just what changed (the diff already shows what).
- **Known follow-ups** (optional) — gaps or pre-existing issues discovered during the
  work that are intentionally out of scope for this branch.
- **Test plan** — a checklist of what was actually verified (manual testing, builds,
  etc.), not a hypothetical list of what could be tested.

**Never commit \`PR_*.md\` files.** They're scratch documents for the PR description.

---

### Building the AD4M Executor Binary (CRITICAL)

The ad4m repo has two artefacts with confusingly similar names:

| Artefact | Cargo flag | Crate location | What it builds |
|---|---|---|---|
| \`ad4m-executor\` **library** | \`-p ad4m-executor\` | \`rust-executor/\` | Library only — **does NOT update the binary** |
| \`ad4m-executor\` **binary** | \`--bin ad4m-executor\` | \`cli/\` (package \`ad4m\`) | The actual executable used by WE |

**Always use \`--bin\` to rebuild the running binary:**
\`\`\`sh
cargo build --release --bin ad4m-executor
\`\`\`

Using \`-p ad4m-executor\` will appear to succeed (Cargo reports "Finished") but the
binary at \`target/release/ad4m-executor\` will NOT be updated — any Rust changes
(log lines, bug fixes) will be silently absent from the running app.

After rebuilding, verify with:
\`\`\`sh
ls -la target/release/ad4m-executor   # timestamp must be fresh
strings target/release/ad4m-executor | grep "your log string"
\`\`\`

**After modifying \`@coasys/ad4m\` TypeScript (e.g. \`core/src/model/Ad4mModel.ts\`):**

The normal pattern is that \`we/package.json\`'s pnpm \`overrides\` pins \`@coasys/ad4m\` to a
**published npm tag**, not a local \`file:\` link. Under that normal pattern, a local
\`cd ad4m/core && pnpm run build\` does NOT get picked up by WE — runtime/logic changes to
\`@coasys/ad4m\` only reach WE once a new tag is published from the ad4m repo and the
override version in \`we/package.json\` is bumped, followed by \`pnpm install\`.

For active local iteration you can temporarily switch the override to
\`"@coasys/ad4m": "file:../ad4m/core"\` (then \`pnpm install\`) so \`pnpm run build\` in
\`ad4m/core\` is picked up directly — just remember to switch it back to the pinned npm tag
before committing \`package.json\`.

Type-only changes (e.g. widening a TS type) don't need any of this — WE's schema types
(\`packages/schema-system/shared/src/types.ts\`) type dynamic query fields (\`where\`,
\`order\`, \`include\`) as loose \`Record<string, unknown>\` shapes, so they pass through
as plain JSON regardless of which \`@coasys/ad4m\` build is installed.

Rust changes to the \`ad4m-executor\` binary are unaffected by any of this — see below.

---

These patterns apply to TypeScript code in stores, services, tests, and scripts
that work directly with AD4M model classes. They do NOT apply to JSON template schemas.

---

### Looking at something that needs other people

Some UI cannot be reached alone. The call stage solves its layout against the panel's box, so
judging it means dragging a real panel around with a real multi-party call running — which one
person cannot start, and which no unit test can answer.

In a development build the call bar carries a \`−  N  +\` pair: press \`+\` and a synthetic
participant with real moving video joins the stage, which re-solves on the click. They join at the
*tile* layer, so the mesh and presence are untouched and this says nothing about signalling — it is
a layout harness. What it does exercise is everything downstream of "there are N participants": the
tiling solve, the spotlight's choice of axis, fit-to-content at each arrangement, the mute badge and
the avatar fallback. The count persists in \`localStorage\` so it survives a reload, and is on screen
so it cannot be silently left on. See \`module-system/call/src/devPeers.ts\`.

Worth copying the shape when another module has the same problem. Two things make it safe and
usable: the whole path is behind \`import.meta.env.DEV\`, spread conditionally into the module's
\`slots\` and store at *definition* time so a production build contains no node and no callable
action rather than an inert one — and the control is where the thing it changes is, rather than a
console incantation, so the loop it exists to support is not broken by leaving the app to use it.

### Rebuilding — scope it to what changed

A full \`pnpm build\` walks the whole monorepo and takes minutes. Reserve it for the end of a piece of
work, where the point is to prove the packages still agree. During iteration, rebuild only what you
touched and what depends on it:

\`\`\`sh
pnpm --filter @we/tokens --filter @we/themes build     # a design-token change
pnpm --filter @we/primitives build                      # a Lit primitive
\`\`\`

**Do rebuild, though — a stale \`dist\` is invisible and wastes more time than the build saves.** Two
symptoms worth recognising, both of which have happened here:

- *"I changed the source and the app is unchanged."* The package ships a \`dist\` and it was not
  rebuilt. Note that packages differ: \`@we/template-shell\` has no \`dist\` and is consumed as source,
  so a change there lands immediately, while \`@we/module-call\` does — which is how the call bar and
  the chrome rail, which are meant to match, ended up different colours from one edit.
- *"The build says it failed but the error names a package I did not touch."* A dependency's types
  moved. Rebuild the chain in dependency order — tokens, then themes, then schema-shared, then
  whatever consumes them.

To find what is stale rather than guessing:

\`\`\`sh
for d in $(find packages -name dist -maxdepth 3 -type d | grep -v node_modules); do
  p=$(dirname $d)
  [ -f "$d/index.js" ] && [ -n "$(find $p/src -newer $d/index.js -name '*.ts*' 2>/dev/null | head -1)" ] && echo "STALE: $p"
done
\`\`\`

Vite caches too. If a rebuilt package still is not picked up by a running dev server, clear
\`node_modules/.vite\` in the app and restart it — an \`ERR_MODULE_NOT_FOUND\` or a "does not provide an
export named X" for something that plainly is exported is the tell.

### Running Schema Validation (no build needed)

During codebase work, use the \`pnpm validate\` script in \`schema-system/shared\` — it runs
the validator directly from TypeScript source via \`tsx\`, so no build step is required:

\`\`\`sh
pnpm --filter @we/schema-shared validate
\`\`\`

This validates every \`.schema.ts\` under \`packages/app-shell/src/shared/schemas/\`,
\`packages/templates/\` (shell, default, views and showcase) and \`packages/module-system/\`. Route and
section files that are not named \`.schema.ts\` are still covered, because the template that composes
them is — the walk descends into whatever a validated schema imports.

Two further audits run over the same trees and are easy to miss. Both **import and walk the composed
tree** rather than grepping source, which is the only way to attribute a node that a fragment from
another package contributed:

\`\`\`sh
pnpm --filter @we/schema-shared role-audit     # colours naming a scale position where a role belongs
pnpm --filter @we/schema-shared surface-audit  # what each surface-sunken is actually sitting on
\`\`\`

Run them after any template, view or fragment change. A \`neutral-600\` label is invisible to the
whole contrast layer — never measured against what is behind it — so \`role-audit\` is the only thing
that will report it.

Two things it now catches that it used to miss, both worth knowing when adding a schema:

- **Every export in a file is checked**, not just the first one found. A fragment file exporting
  several sections used to be judged on whichever happened to be declared at the top.
- **A schema that fails to import is an error**, not a skip. It used to print the failure and still
  exit 0, so an unloadable schema looked identical to a clean one.

Asset imports (\`import cover from './cover.jpg'\`) resolve to a stub, so a schema that references
an image validates without a bundler. See \`src/cli/assetHooks.mjs\`.

For per-file validation or other options, see the **Schema Validation** section above.

---

### Schema System — Before Suggesting New Operators

Before proposing a new schema operator, read \`packages/schema-system/OPERATORS.md\` —
the full operator set is documented there. Adding a new one is only warranted if the
operator genuinely doesn't exist AND the workaround requires 3+ levels of nesting.

Operators that are easy to miss:

| Operator | Syntax | What it does |
|---|---|---|
| \`$in\` | \`{ $in: [value, array] }\` | True if array contains value — array membership check |
| \`$find\` | \`{ $find: { items, where } }\` | Returns the first matching item (or null) |
| \`$pick\` | \`{ $pick: { from, keys } }\` | Extracts a subset of keys from an object |
| \`$map\` | \`{ $map: { items, as, value } }\` | Maps an array to a new array of values |
| \`$ne\` | \`{ $ne: [a, b] }\` | Not-equal comparison |
| \`$concat\` | \`{ $concat: [part, ...] }\` | Joins strings: \`['neighbourhood://', '$space.url']\` |

**Common mistake:** reaching for \`$filter + $count + $gt\` to check array membership
when \`$in\` already exists. Example:

\`\`\`ts
// ❌ Verbose — don't do this for a simple membership check
{ $gt: [{ $count: { items: { $filter: { items: arr, where: { id: val } } } } }, 0] }

// ✅ Use $in instead
{ $in: [val, arr] }
\`\`\`

**Common mistake:** wrapping \`$count\` in \`$gt [..., 0]\` when used as a \`$if\` condition.
\`$if\` conditions use standard JavaScript truthiness — \`0\` is falsy, any positive number is truthy.
The \`$gt\` layer is redundant nesting that produces no change in behaviour.

\`\`\`ts
// ❌ Unnecessary — $gt adds nothing here
{ "condition": { "$gt": [{ "$count": { "items": { "$local": "items" } } }, 0] } }

// ✅ $count alone is truthy/falsy in a condition
{ "condition": { "$count": { "items": { "$local": "items" } } } }
\`\`\`

Note: \`$gt\` is still needed when you want an explicit boolean value outside a condition context
(e.g. as a prop that expects \`boolean\`, not just any truthy value).

---

### Package Conventions

Each package may have a \`CONVENTIONS.md\` at its root with package-specific rules.
Always read \`CONVENTIONS.md\` before creating or modifying files in that package.

Key packages with conventions files:
- \`packages/design-system/2-themes/THEME_AUTHORING.md\` — **read this before writing or editing a
  theme.** A theme is an object of numbers, not a stylesheet: polarity plus a lightness range, hues
  as OKLCH angles (blue is 263, not 220), saturation as a fraction of what the hue can hold, and
  roles pinned only where the parametric default is wrong. Several roles are *derived at apply time*
  — foregrounds, fills and interaction states all correct themselves — so pinning them is overruling
  a measurement, which is occasionally right and usually not.
- \`packages/models/CONVENTIONS.md\` — model authoring: entities vs blocks, predicates, @Flag, WeNode, Model.create() pattern
- \`packages/templates/kit/CONVENTIONS.md\` — fragment authoring: what belongs in the kit, extraction threshold, options-object API, body style

---

### Model CRUD Patterns

Use the static factory method for creation. **Never** use \`new Model() + manual property assignment + save()\`.

**Create**
\`\`\`ts
const space = await Space.create(perspective, {
  uuid: crypto.randomUUID(),
  name: 'My Space',
  description: 'A description',
  visibility: 'public',
});
\`\`\`

**Read all**
\`\`\`ts
const spaces = await Space.findAll(perspective);
\`\`\`

**Read one** (first match by property)
\`\`\`ts
const space = await Space.findOne(perspective, { where: { name: 'My Space' } });
\`\`\`

**Read by id** — there is no \`findById\`; use \`findOne\` with a \`where\` clause:
\`\`\`ts
// ✅ Correct
const space = await Space.findOne(perspective, { where: { id } });

// ❌ Wrong — findById does not exist
const space = await Space.findById(perspective, id);
\`\`\`

**Update**
\`\`\`ts
space.name = 'New Name';
await space.save();
\`\`\`

**Delete**
\`\`\`ts
await space.delete();
\`\`\`

**HasMany relations**
\`\`\`ts
await space.addLocations(locationBlock);     // add<RelationName>(instance)
const locs = await space.getLocations();     // get<RelationName>()
await space.removeLocations(locationBlock);  // remove<RelationName>(instance)
\`\`\`

Accessor names derive from the \`@HasMany\` property name: e.g. \`locations\` → \`addLocations\` / \`getLocations\` / \`removeLocations\`.

---

### Include / Projection Patterns

Relations declared with \`@HasMany\` or \`@HasOne\` can be eagerly loaded or counted
in the same query using the \`include\` option on \`findAll\` / \`findOne\`.

**Eager-load a relation (full instances)**
\`\`\`ts
// signals is declared on WeNode as \`signals: string[]\`. Include hydrates
// the URIs into Signal instances at runtime, but the static field type stays
// string[] (it reflects the unhydrated state). Cast to read the instances:
const nodes = await Space.findAll(perspective, { include: { signals: true } });
const sigs = nodes[0].signals as unknown as Signal[];
\`\`\`

**Count a relation (number, no instances fetched)**

Use a \`$\`-prefixed key with \`{ from, count: true }\`. The projection key flows
into the result row's type via \`IncludeExtras\`, so the value is typed directly:
\`\`\`ts
const spaces = await Space.findAll(perspective, {
  include: { $signalCount: { from: 'signals', count: true } },
});
const n: number = spaces[0].$signalCount ?? 0;
\`\`\`

**Filtered subset — named \`$\`-projection returning instances**

Use a \`$\`-prefixed key with \`{ from, where, limit }\`. The matched instances are
attached to each result under that key. With \`limit: 1\` the value is the scalar
or \`null\`; without a limit (or with limit > 1) it's an array:
\`\`\`ts
const spaces = await Space.findAll(perspective, {
  include: {
    $mySignal: {
      from: 'signals',
      where: { signalTypeId: 'some-id', author: myDid },
      limit: 1,
    },
  },
});
const mySignal = spaces[0].$mySignal; // Signal | null — typed via IncludeExtras
\`\`\`

In JSON schema nodes the \`where\` values are resolved tokens. Signal types have no store accessor —
resolve one by slug from a hoisted \`$queries\` subscription (see the Signal types pattern above):
\`\`\`ts
// Schema node — tokens resolved at render time
$queries: { signalTypes: { entity: 'SignalType', subscribe: true } },
// …
include: {
  $myLikeSignal: {
    from: 'signals',
    where: {
      signalTypeId: { $find: { items: { $local: 'signalTypes' }, where: { slug: 'like' }, select: 'id' } },
      author: '$me.did',
    },
    limit: 1,
  },
}
// Access the result: '$post.$myLikeSignal.value'
\`\`\`

Note: \`count: true\` works as a plain literal — the typed projection (\`TypedIncludeProjection\`)
contextually narrows it to the \`true\` literal, so the \`as const\` workaround is no longer needed.

---

### Signal Predicate

Signals on any \`WeNode\` subclass (Space, AgentProfile, TextBlock, …) use the
predicate **\`we://signal\`** — the relation is declared as:
\`\`\`ts
@HasMany(() => Signal, { through: 'we://signal' })
signals: string[] = [];
\`\`\`

When creating a signal manually (not via the ORM relation helpers), pass the
correct predicate to the \`parent\` option:
\`\`\`ts
await Signal.create(perspective, { signalTypeId, value }, {
  parent: { id: nodeId, predicate: 'we://signal' },
});
\`\`\`

**\`we://has_signals\` is wrong** — it is a different predicate that the ORM does not
know about. Using it creates orphaned links invisible to \`include: { signals: true }\`.

---

**Anti-pattern — do not use:**
\`\`\`ts
// ❌ Wrong
const space = new Space(perspective);
space.uuid = crypto.randomUUID();
space.name = 'My Space';
await space.save();

// ✅ Correct
const space = await Space.create(perspective, { uuid: crypto.randomUUID(), name: 'My Space' });
\`\`\`

---

### Solid + Lit Web Component Event Handling

**How the event type generator works** (\`packages/design-system/3-primitives/scripts/generate-framework-declarations.ts\`):

For Solid, two categories of event props are generated per element:
- **Native DOM events** → camelCase delegated handlers (\`onClick\`, \`onInput\`, \`onChange\`, etc.) via Solid's synthetic delegation system
- **Custom Lit events** declared in the Custom Elements Manifest → \`'on:eventname'\` direct listeners (e.g. \`'on:select'\`, \`'on:toggle'\`)

The \`on:eventname\` syntax is Solid's escape hatch for adding a direct \`addEventListener\` on the host element, bypassing delegation entirely.

**\`we-menu-item\` — always use \`on:select\`, not \`onClick\`**

\`we-menu-item\` dispatches a \`select\` CustomEvent (composed, bubbles) when clicked — this is its designed public API. The generated Solid type already includes \`'on:select'?: (event: CustomEvent) => void\`.

\`\`\`tsx
// ✅ Correct — uses designed API, already typed, works through shadow DOM + popover
<we-menu-item value={opt.value} on:select={() => handleSelect(opt)}>
  <we-text>{opt.label}</we-text>
</we-menu-item>

// ❌ Wrong — 'on:click' is not in the generated type (TypeScript error)
<we-menu-item value={opt.value} on:click={() => handleSelect(opt)}>

// ❌ Unreliable — onClick uses Solid delegation which may not reach elements
// inside shadow DOM or we-popover's browser top-layer
<we-menu-item value={opt.value} onClick={() => handleSelect(opt)}>
\`\`\`

**Why delegation fails inside \`we-popover\`**: Solid's delegated events (\`onClick\`, etc.) are registered at the Solid root element. Events from inside shadow DOM stacks or the browser's Popover API top layer may not reach the delegation root correctly due to shadow boundary retargeting. Always prefer \`on:select\` for \`we-menu-item\` — it adds a direct listener on the host element itself.

**General rule for other web component events**: if you need to listen to a native DOM event (e.g. \`click\`, \`input\`) on a \`we-\` primitive inside a deep shadow DOM context and \`onClick\`/\`onInput\` prove unreliable, use a \`ref\` callback with \`addEventListener\` directly — this never has delegation issues:
\`\`\`tsx
<we-some-element ref={(el) => el.addEventListener('click', handler)} />
\`\`\`

---

### Shadow DOM + Slots: Third-party Library Root Detection

Lit primitives (\`we-scroll-area\`, \`we-popover\`, etc.) use Shadow DOM with \`<slot>\`.
Light-DOM children are slotted through, but their \`assignedSlot\` property points into
the Shadow Root. Any library that auto-detects its document root by walking up via
\`assignedSlot\` will end up scoped to the **ShadowRoot** rather than the main document.

**Symptoms when a library is incorrectly scoped to a ShadowRoot:**
- Styles injected by the library don't apply to its own DOM elements (which live in the light DOM)
- \`document.activeElement\` checks fail because the library checks \`shadowRoot.activeElement\` instead
- Everything works only after another instance of the same library mounts outside the web component

**Known affected library: CodeMirror 6**

CM6's \`getRoot()\` follows \`assignedSlot\` into the Shadow Root. Symptoms: editor shows
only the gutter (unstyled), cursor/focus detection broken. Fix: always pass
\`root: containerRef.ownerDocument\` to the \`EditorView\` constructor. \`ownerDocument\`
skips the slot chain and always returns the main \`Document\`.

\`\`\`tsx
// ✅ Always do this when mounting a CodeMirror EditorView inside any we-* component
view = new EditorView({
  parent: containerRef,
  root: containerRef.ownerDocument,
  ...
});
\`\`\`

**General rule for other libraries**: if a third-party library accepts a \`document\`,
\`root\`, or \`container\` option and uses it for style injection or focus detection,
pass \`element.ownerDocument\` explicitly rather than letting the library auto-detect.
`;
