/**
 * Developer patterns fragment.
 *
 * This content is included in IDE instruction files (copilot-instructions.md,
 * CLAUDE.md, cursor rules) but intentionally EXCLUDED from the in-app AI context
 * (schemaContext.ts) because it is irrelevant when an AI is editing JSON templates.
 *
 * Add patterns here that help IDEs / terminal agents working directly in the
 * TypeScript codebase (stores, services, tests, scripts).
 */

export const devPatterns = `
## Developer Patterns (codebase work — not for JSON schema authoring)

---

### Using the Design System in TypeScript Components

When writing Solid TSX components (stores, editor panels, settings UI, etc.), always
reach for design system primitives before writing raw HTML elements with inline styles.

**Layout:** Use \`Column\`, \`Row\`, and \`Grid\` from \`@we/components/solid\` for all
flex and grid layouts. DS props (\`gap\`, \`p\`, \`px\`, \`bg\`, \`r\`, \`border\`, etc.)
cover the vast majority of layout needs without inline styles.
- \`Grid\` supports uniform columns (\`columns={3}\`), responsive auto-fill
  (\`minChildWidth="280px"\`), and custom templates (\`template="28px 1fr 28px"\`).
- Use the \`styles\` prop only for CSS that genuinely has no DS equivalent.

**Text:** Use \`we-text\` with its own props (\`fontSize\`, \`fontWeight\`, \`color\`,
\`truncate\`, \`variant\`, etc.) rather than passing everything through \`style={{}}\`.

**Interactive controls:** Use \`we-button\`, \`we-input\`, \`we-checkbox\`, \`we-select\`,
\`we-switch\` etc. — they bring theming, focus rings, hover states, and accessibility
for free. Never roll custom \`<button>\` or \`<input>\` elements when a primitive fits.

**Scrollable areas:** Use \`we-scroll-area\` instead of \`overflow: auto\` on a div —
it gives consistently styled scrollbars across themes.

**Dividers:** Use \`we-divider\` or the \`borderBottom\`/\`borderTop\` DS prop on a
\`Column\`/\`Row\` rather than a raw \`<hr>\` or border on a wrapper div.

**Token values:** Use \`tokenVar\` from \`@we/design-utils\` when you need a token value
inside a \`style={{}}\` object. Prefer DS props directly where possible.

**Name a colour ROLE, in code as well as in a schema.** \`tokenVar('color', 'text-muted')\`, not
\`tokenVar('color', 'neutral-600')\` — a step is invisible to the contrast corrections at apply time
wherever it is written, and \`tokenVar\` accepts a role name directly. \`pnpm audit:roles\` covers the
TypeScript and SCSS as well as the schemas, and gates CI.

Note what \`tokenVar\` does with a name it does not know: it warns in development and returns
\`var(--we-color-<name>)\` anyway, so a typo or an invented family compiles to a variable nothing
declares and the declaration is dropped. The element paints nothing, which reads as a design
decision rather than a bug.

Raw inline styles and hardcoded CSS variable strings (\`var(--we-color-neutral-400)\`)
are a signal that a DS prop or primitive is being missed — check before reaching for
\`style={{}}\`.

---

### Auto-generated Files — Never Edit Directly

The following files are fully regenerated by \`pnpm --filter @we/ai-context generate-context\`.
**Never edit them manually** — changes will be overwritten on the next generation run.

| File | Source to edit instead |
|---|---|
| \`CLAUDE.md\` | \`packages/ai-context/src/fragments/\` |
| \`AGENTS.md\` | \`packages/ai-context/src/fragments/\` |
| \`.github/copilot-instructions.md\` | \`packages/ai-context/src/fragments/\` |
| \`.cursor/rules/we-schema.mdc\` | \`packages/ai-context/src/fragments/\` |
| \`packages/ai-context/src/schemaContext.ts\` | \`packages/ai-context/src/fragments/\` or \`assembler.ts\` |
| \`packages/ai-context/src/contextData.ts\` | \`packages/ai-context/src/generate.ts\` or \`storeEntries\` |

To add or change documented schema fields, tokens, conventions, or rules:
1. Edit the appropriate fragment in \`packages/ai-context/src/fragments/\`
2. Run \`pnpm --filter @we/ai-context generate-context\` to regenerate all output files
3. Commit both the fragment source change and the regenerated files together

---

### Git Workflow — Default Branch & PR Summaries

\`main\` is the production branch — it only receives periodic merges for releases, each tagged
\`v<version>\` (the release steps are in \`docs/contributing/ad4m-and-deploys.md\`).
\`dev\` is where all active work happens. Always branch from \`dev\`, and always
diff/compare against \`dev\` (e.g. \`git diff dev...HEAD\`, \`git log dev..HEAD\`) —
never \`main\`, even though it exists.

**PR summary convention:** a PR description follows \`docs/contributing/pull-requests.md\`. When
asked to write one for a branch, create \`PR_<DESCRIPTIVE_NAME>.md\` at the repo root, based on
\`git diff dev...<branch>\` and the branch's commit log, with these sections:

- **What** — what merging it changes, in a few bullets.
- **Why** — the problem, and why this is the right fix for it.
- **How** — where a reviewer should start and the route through the change; a table of files when
  it is wide, explaining *why* each changed rather than restating the diff.
- **Test plan** — what was actually verified, ticked, and what was not, unticked with the reason.

**Never commit \`PR_*.md\` files.** They're scratch documents for the PR description.

---

### Building the AD4M Executor Binary (CRITICAL)

The ad4m repo has two artefacts with confusingly similar names:

| Artefact | Cargo flag | Crate location | What it builds |
|---|---|---|---|
| \`ad4m-executor\` **library** | \`-p ad4m-executor\` | \`rust-executor/\` | Library only — **does NOT update the binary** |
| \`ad4m-executor\` **binary** | \`--bin ad4m-executor\` | \`cli/\` (package \`ad4m\`) | The actual executable used by WE |

**Always use \`--bin\` to rebuild the running binary:**
\`\`\`sh
cargo build --release --bin ad4m-executor
\`\`\`

Using \`-p ad4m-executor\` will appear to succeed (Cargo reports "Finished") but the
binary at \`target/release/ad4m-executor\` will NOT be updated — any Rust changes
(log lines, bug fixes) will be silently absent from the running app.

After rebuilding, verify with:
\`\`\`sh
ls -la target/release/ad4m-executor   # timestamp must be fresh
strings target/release/ad4m-executor | grep "your log string"
\`\`\`

**After modifying \`@coasys/ad4m\` TypeScript (e.g. \`core/src/model/Ad4mModel.ts\`):**

The root \`package.json\`'s pnpm \`overrides\` pin \`@coasys/ad4m\` and \`@coasys/ad4m-connect\` to a
**published version**, not a local \`file:\` link, and every WE build uses that pin except a deploy
preview whose PR description pairs it with an ad4m change. The pairing is this exact block, first in
the description — anything close (no colon, another heading or alert, lower down, the old
\`ad4m: coasys/ad4m#<N>\` line) is an error, not a pairing:

\`\`\`markdown
> [!IMPORTANT]
> ### Paired with: coasys/ad4m#<N>
\`\`\`

So a local
\`cd ad4m/core && pnpm run build\` does NOT get picked up by WE — changes to \`@coasys/ad4m\` reach WE
once a version is published from the ad4m repo and the pin moves. A bot keeps one PR open that moves
it to the newest ad4m \`dev\` version (\`.github/workflows/bump-ad4m.yaml\`); a feature that needs a
new ad4m moves it in its own PR with \`pnpm bump:ad4m\`. Run \`pnpm verify:ad4m\` before merging either. The whole policy is in
\`docs/contributing/ad4m-and-deploys.md\`.

For active local iteration you can temporarily switch the override to
\`"@coasys/ad4m": "file:../ad4m/core"\` (then \`pnpm install\`) so \`pnpm run build\` in
\`ad4m/core\` is picked up directly — just remember to switch it back to the pinned npm tag
before committing \`package.json\`.

Type-only changes (e.g. widening a TS type) don't need any of this — WE's schema types
(\`packages/schema-system/shared/src/types.ts\`) type dynamic query fields (\`where\`,
\`order\`, \`include\`) as loose \`Record<string, unknown>\` shapes, so they pass through
as plain JSON regardless of which \`@coasys/ad4m\` build is installed.

Rust changes to the \`ad4m-executor\` binary are unaffected by any of this — see below.

---

These patterns apply to TypeScript code in stores, services, tests, and scripts
that work directly with AD4M model classes. They do NOT apply to JSON template schemas.

---

### Looking at something that needs other people

Some UI cannot be reached alone. The call stage solves its layout against the panel's box, so
judging it means dragging a real panel around with a real multi-party call running — which one
person cannot start, and which no unit test can answer.

In a development build the call bar carries a \`−  N  +\` pair: press \`+\` and a synthetic
participant with real moving video joins the stage, which re-solves on the click. They join at the
*tile* layer, so the mesh and presence are untouched and this says nothing about signalling — it is
a layout harness. What it does exercise is everything downstream of "there are N participants": the
tiling solve, the spotlight's choice of axis, fit-to-content at each arrangement, the mute badge and
the avatar fallback. The count persists in \`localStorage\` so it survives a reload, and is on screen
so it cannot be silently left on. See \`module-system/call/src/devPeers.ts\`.

Worth copying the shape when another module has the same problem. Two things make it safe and
usable: the whole path is behind \`import.meta.env.DEV\`, spread conditionally into the module's
\`slots\` and store at *definition* time so a production build contains no node and no callable
action rather than an inert one — and the control is where the thing it changes is, rather than a
console incantation, so the loop it exists to support is not broken by leaving the app to use it.

### Rebuilding — scope it to what changed

A full \`pnpm build\` walks the whole monorepo and takes minutes. Reserve it for the end of a piece of
work, where the point is to prove the packages still agree. During iteration, rebuild only what you
touched and what depends on it:

\`\`\`sh
pnpm --filter @we/tokens --filter @we/themes build     # a design-token change
pnpm --filter @we/primitives build                      # a Lit primitive
\`\`\`

**Do rebuild, though — a stale \`dist\` is invisible and wastes more time than the build saves.** Three
symptoms worth recognising, all of which have happened here:

- *"I changed the source and the app is unchanged."* The package ships a \`dist\` and it was not
  rebuilt. Note that packages differ: \`@we/template-shell\` has no \`dist\` and is consumed as source,
  so a change there lands immediately, while \`@we/module-call\` does — which is how the call bar and
  the chrome rail, which are meant to match, ended up different colours from one edit.
- *"The build says it failed but the error names a package I did not touch."* A dependency's types
  moved. Rebuild the chain in dependency order — tokens, then themes, then schema-shared, then
  whatever consumes them.
- *"The adapter's test still sees the old behaviour."* A test that imports \`@we/backend-ad4m\` by its
  own name resolves through the package's \`exports\` to \`dist\`, so it runs the last build rather than
  \`src\`. Rebuild the package before \`pnpm --filter @we/backend-ad4m test\`.

To find what is stale rather than guessing:

\`\`\`sh
for d in $(find packages -name dist -maxdepth 3 -type d | grep -v node_modules); do
  p=$(dirname $d)
  [ -f "$d/index.js" ] && [ -n "$(find $p/src -newer $d/index.js -name '*.ts*' 2>/dev/null | head -1)" ] && echo "STALE: $p"
done
\`\`\`

Vite caches too. If a rebuilt package still is not picked up by a running dev server, clear
\`node_modules/.vite\` in the app and restart it — an \`ERR_MODULE_NOT_FOUND\` or a "does not provide an
export named X" for something that plainly is exported is the tell.

### Running Schema Validation (no build needed)

During codebase work, use the \`pnpm validate\` script in \`schema-system/shared\` — it runs
the validator directly from TypeScript source via \`tsx\`, so no build step is required:

\`\`\`sh
pnpm --filter @we/schema-shared validate
\`\`\`

This validates every \`.schema.ts\` under \`packages/app-shell/src/shared/schemas/\`,
\`packages/templates/\` (shell, default, views and showcase) and \`packages/module-system/\`. Route and
section files that are not named \`.schema.ts\` are still covered, because the template that composes
them is — the walk descends into whatever a validated schema imports.

Further audits run over the same trees and are easy to miss. They all **import and walk the composed
tree** rather than grepping source, which is the only way to attribute a node that a fragment from
another package contributed:

\`\`\`sh
pnpm audit:roles                               # a scale position where a role belongs
pnpm audit:surfaces                            # a surface-sunken invisible against its ground
pnpm --filter @we/schema-shared tooltip-audit  # nodes asking the browser for a tooltip via \`title\`
pnpm --filter @we/schema-shared query-audit    # queries that read a growing list whole
pnpm --filter @we/schema-shared size-audit     # how big each template is, and what it says twice
\`\`\`

Run them after any template, view or fragment change. A \`neutral-600\` label is invisible to the
whole contrast layer — never measured against what is behind it — so \`role-audit\` is the only thing
that will report it.

**The first two gate CI**, so a scale position or an invisible well fails the build rather than
waiting to be noticed. Both are at zero; keep them there.

\`role-audit\` has a **code half** as well, which the root script runs by default: paths after
\`--code\` are scanned textually rather than imported, because a colour in a \`style={{}}\`, an
\`.scss\` rule or a CodeMirror theme is a string in a file and there is no tree to walk. It reads
four spellings — \`var(--we-color-<hue>-<step>)\`, \`tokenVar('color', '<hue>-<step>')\`, a DS prop in
TSX (\`color="neutral-800"\`), and a raw hex or \`rgb()\` next to a property that paints — plus a name
handed to \`tokenVar\` that is **no colour at all**, which compiles to a variable nothing declares and
paints nothing. Four of the editor's dividers were \`ui-200\`, a ramp that has never existed.

A genuine palette is exempt, with its reason, in one of two places: \`CODE_PALETTES\` for a whole file
(syntax highlighting, a WebGL scene, a theme's own definitions) or a \`role-audit: palette\` marker in
the comment above the line, for a file that is mostly chrome and has one swatch. The reasons print on
every run. \`EditorOverlay\` is the case worth reading: its annotation colours are fixed on purpose,
because they are drawn over the template being edited in whatever theme its author is choosing.

\`surface-audit\` judges a well by what is behind it rather than by the roles table's wording, which
is looser than the ramp. \`surface-sunken\` is derived from \`page\`, so a trough on the page is right;
on \`chrome\` it is half a lightness point away and **inverts** between light and dark, and on another
\`surface-sunken\` there is no difference at all. Those two fail.

\`query-audit\` is the one whose findings are invisible in development and expensive in a real space.
A \`$query\` with no \`limit\` re-reads, re-hydrates and re-fingerprints every row of its entity on
every change to that entity, so a list that grows costs O(n²) over a session — fine at twenty rows
and unusable at two thousand, which is a transcript after forty minutes. It reports only what
nothing else bounds: \`where.id\`, a \`scope\` with \`levels\` or \`limitPerAnchor\`, and a curated
vocabulary all count as bounded. A list that really is read whole on purpose is declared in
\`DELIBERATE\` in the script, **with the reason**, and the reasons are printed on every run so they
get reviewed rather than accumulated.

Two things about its reach, both worth knowing when adding a schema:

- **Every export in a file is checked**, not just the first one found — so a fragment file
  exporting several sections is judged on all of them.
- **A schema that fails to import is an error**, not a skip, so an unloadable schema cannot look
  identical to a clean one.

\`size-audit\` measures what a template COSTS to carry around, which is a different question from
whether it is correct. A template is data, and everything downstream pays for its size by the
character: the editor sends the whole schema to a language model on every turn and gets a whole
schema back, the undo history holds a copy per edit, and a template crossing the wire carries all
of it. The hard limit is a model's context window, so a shape written twice is not untidy — it
halves what can be reasoned about.

It reports two things per schema, and they want different answers:

- **\`$if sides share N chars\`** is a branch pair whose two sides say some of the same thing. This
  is the one to fix, and the fix is usually one node with the condition in its props rather than a
  \`$if\` holding the content down both sides — the same DOM, half the bytes, no new machinery.
  \`buildCard\` in \`@we/schema-kit\` was exactly that, at 150,445 characters a copy in \`CardsView\`.
- **\`repeat ×N\`** is a shape written out N times, which is usually a FRAGMENT called N times and
  not a defect at all: a tree cannot name a shape and point at it, so a fragment's output is a
  copy by construction. Reported because it is where the cost is, not because there is an edit.

Neither gates CI. Size is a judgement — a rich template is big — and the honest summary is the
\`gzip\` ratio beside it: around 4× means a template that says each thing once, and past about 8×
means most of it is repetition. Pass \`--show\` to print the head of each repeated subtree, without
which the report names a shape it gives no way to find.

Asset imports (\`import cover from './cover.jpg'\`) resolve to a stub, so a schema that references
an image validates without a bundler. See \`src/cli/assetHooks.mjs\`.

For per-file validation or other options, see the **Schema Validation** section above.

---

### Schema System — The Grammar Is Closed

**No new value operators, and no new syntax.** The value layer is one expression language —
\`{ "$": "count(local.rows) > 0 && local.search != ''" }\` — with a closed grammar (references,
comparison, boolean and arithmetic operators, interpolation, a ternary, five comprehension macros)
and an open **function library** (\`packages/schema-system/shared/src/expressions/functions.ts\`).
There are no other value tokens: a store read, a local read, a comparison, a count, a label — each
is an expression, and a plain string anywhere in a schema is text.

A need for computation the language lacks is answered on the **code** side of the data/code line:

- **A function in the library** — \`defineFunction({ name, category, params, doc, example, impl })\`.
  Pure and total: wrong-typed input answers with the empty value of its kind, never a throw. Same
  bar as a component: three real uses, not one. The generated context lists it from the registry, so
  there is no doc to update.
- **A host source** — a function this deployment registers in
  \`packages/app-shell/src/shared/sources/index.ts\`, reachable as \`calendarMonth({ … })\`.
  Catalogued from the registry into the context and known to the validator.

Neither changes the parser, the validator's grammar, the renderer or the LLM's view of the syntax.
That is the whole reason for the split: the accretion pressure that produced forty operators now
lands where a docblock and a registry entry absorb it.

**Common mistake:** rebuilding a library function out of operators. \`count(filter(arr, { id: val })) > 0\`
is \`val in arr\` — hmm, no: it is \`arr.exists(x, x.id == val)\`; \`val in arr\` tests the values
themselves. Read the library table in the schema reference before composing.

**Common mistake:** \`count(local.items) > 0\` as a \`$if\` condition. Conditions use truthiness; \`0\`
is falsy, so \`count(local.items)\` alone is the condition. Keep the comparison where a prop wants a
real boolean — \`&&\`/\`||\` already answer with one.

**Handlers stay tokens.** \`$action\`, \`$setLocal\`, \`$toggleLocal\`, \`$toggleLocalIn\`, \`$callLocal\`,
\`$touch\`, \`$resetLocal\` are the statement layer — about seven verbs, enumerable on purpose because
capability grants and \`destructive\` flags attach to verbs. Their *arguments* take expressions, and an
expression naming \`event\`/\`arg\`/\`result\` at the top level of \`args\` or as a \`$setLocal\` \`value\`
is evaluated when the handler fires.

---

### Package Conventions

Each package may have a \`CONVENTIONS.md\` at its root with package-specific rules.
Always read \`CONVENTIONS.md\` before creating or modifying files in that package.

Key packages with conventions files:
- \`packages/design-system/2-themes/THEME_AUTHORING.md\` — **read this before writing or editing a
  theme.** A theme is an object of numbers, not a stylesheet: polarity plus a lightness range, hues
  as OKLCH angles (blue is 263, not 220), saturation as a fraction of what the hue can hold, and
  roles pinned only where the parametric default is wrong. Several roles are *derived at apply time*
  — foregrounds, fills and interaction states all correct themselves — so pinning them is overruling
  a measurement, which is occasionally right and usually not.
- \`packages/entities/CONVENTIONS.md\` — entity authoring: what makes one a block, predicates, @Flag, WeNode, the Entity.create() pattern
- \`packages/templates/kit/CONVENTIONS.md\` — fragment authoring: what belongs in the kit, extraction threshold, options-object API, body style

---

### Record CRUD Patterns

A record is written through its entity's class. Use the static factory method for creation —
**never** \`new Entity() + manual property assignment + save()\`.

**Create**
\`\`\`ts
const space = await Space.create(perspective, {
  uuid: crypto.randomUUID(),
  name: 'My Space',
  description: 'A description',
  visibility: 'public',
});
\`\`\`

**Read all**
\`\`\`ts
const spaces = await Space.findAll(perspective);
\`\`\`

**Read one** (first match by property)
\`\`\`ts
const space = await Space.findOne(perspective, { where: { name: 'My Space' } });
\`\`\`

**Read by id** — there is no \`findById\`; use \`findOne\` with a \`where\` clause:
\`\`\`ts
// ✅ Correct
const space = await Space.findOne(perspective, { where: { id } });

// ❌ Wrong — findById does not exist
const space = await Space.findById(perspective, id);
\`\`\`

**Update**
\`\`\`ts
space.name = 'New Name';
await space.save();
\`\`\`

**Delete**
\`\`\`ts
await space.delete();
\`\`\`

**HasMany relations**
\`\`\`ts
await space.addLocations(locationBlock);     // add<RelationName>(instance)
const locs = await space.getLocations();     // get<RelationName>()
await space.removeLocations(locationBlock);  // remove<RelationName>(instance)
\`\`\`

Accessor names derive from the \`@HasMany\` property name: e.g. \`locations\` → \`addLocations\` / \`getLocations\` / \`removeLocations\`.

---

### Include / Projection Patterns

Relations declared with \`@HasMany\` or \`@HasOne\` can be eagerly loaded or counted
in the same query using the \`include\` option on \`findAll\` / \`findOne\`.

**Eager-load a relation (full instances)**
\`\`\`ts
// signals is declared on WeNode as \`signals: string[]\`. Include hydrates
// the URIs into Signal instances at runtime, but the static field type stays
// string[] (it reflects the unhydrated state). Cast to read the instances:
const nodes = await Space.findAll(perspective, { include: { signals: true } });
const sigs = nodes[0].signals as unknown as Signal[];
\`\`\`

**Count a relation (number, no instances fetched)**

Use a \`$\`-prefixed key with \`{ from, count: true }\`. The projection key flows
into the result row's type via \`IncludeExtras\`, so the value is typed directly:
\`\`\`ts
const spaces = await Space.findAll(perspective, {
  include: { $signalCount: { from: 'signals', count: true } },
});
const n: number = spaces[0].$signalCount ?? 0;
\`\`\`

**Filtered subset — named \`$\`-projection returning instances**

Use a \`$\`-prefixed key with \`{ from, where, limit }\`. The matched instances are
attached to each result under that key. With \`limit: 1\` the value is the scalar
or \`null\`; without a limit (or with limit > 1) it's an array:
\`\`\`ts
const spaces = await Space.findAll(perspective, {
  include: {
    $mySignal: {
      from: 'signals',
      where: { signalTypeId: 'some-id', author: myDid },
      limit: 1,
    },
  },
});
const mySignal = spaces[0].$mySignal; // Signal | null — typed via IncludeExtras
\`\`\`

In JSON schema nodes the \`where\` values are resolved tokens. Signal types have no store accessor —
resolve one by slug from a hoisted \`$queries\` subscription (see the Signal types pattern above):
\`\`\`ts
// Schema node — tokens resolved at render time
$queries: { signalTypes: { entity: 'SignalType', subscribe: true } },
// …
include: {
  $myLikeSignal: {
    from: 'signals',
    where: {
      signalTypeId: { $: "find(local.signalTypes, { slug: 'like' }).id" },
      author: { $: 'me.did' },
    },
    limit: 1,
  },
}
// Access the result: { $: 'post.$myLikeSignal.value' }
\`\`\`

Note: \`count: true\` works as a plain literal — the typed projection (\`TypedIncludeProjection\`)
contextually narrows it to the \`true\` literal, so it needs no \`as const\`.

---

### Signal Predicate

Signals on any \`WeNode\` subclass (Space, AgentProfile, TextBlock, …) use the
predicate **\`we://signal\`** — the relation is declared as:
\`\`\`ts
@HasMany(() => Signal, { through: 'we://signal' })
signals: string[] = [];
\`\`\`

When creating a signal manually (not via the ORM relation helpers), pass the
correct predicate to the \`parent\` option:
\`\`\`ts
await Signal.create(perspective, { signalTypeId, value }, {
  parent: { id: nodeId, predicate: 'we://signal' },
});
\`\`\`

**\`we://has_signals\` is wrong** — it is a different predicate that the ORM does not
know about. Using it creates orphaned links invisible to \`include: { signals: true }\`.

---

**Anti-pattern — do not use:**
\`\`\`ts
// ❌ Wrong
const space = new Space(perspective);
space.uuid = crypto.randomUUID();
space.name = 'My Space';
await space.save();

// ✅ Correct
const space = await Space.create(perspective, { uuid: crypto.randomUUID(), name: 'My Space' });
\`\`\`

---

### Watching the graph from \`@we/backend-ad4m\`

To hear that something changed in a perspective, subscribe on the executor with \`subscribeQuery\`
rather than \`addListener('link-added' | 'link-removed')\`. A link listener receives every link of a
peer-sync burst in JS and filters there. The executor re-runs a subscription only for a diff that
touches one of its predicates, and pushes only when the result changes.

That filter needs SPARQL that writes each predicate out as a full \`<iri>\`: the executor reads the
predicates from the query text. A variable predicate (even one a \`FILTER\` pins down), a prefixed
name, or a Prolog query makes it re-run the subscription on every diff. \`onProposalsChanged\` in
\`interpretationAdapter.ts\` shows the pattern, and \`interpretationDecisions.test.ts\` pins its query.

What the SDK and executor do around a subscription, so a watch can rely on it:

- A callback registered after \`subscribeQuery\` resolves does not receive the initial result — only
  the changes after it.
- After a websocket reconnect, the SDK re-subscribes and hands the current result to every
  callback, so a watch hears a refresh rather than nothing.
- The executor shares one server-side subscription between identical queries from the same user.
  Disposing one ends it for the other too, until the other's 30-second keepalive fails and
  re-subscribes. So hold one subscription per perspective and query, count its holders, and dispose
  it a grace period after the last one lets go — \`onProposalsChanged\` shows how. The grace matters:
  a dispose racing a fresh subscribe with the same text can land after it and end that one too.

### Reading shapes from \`@we/backend-ad4m\`

The \`PerspectiveProxy\` the app holds comes from the SDK copy bundled inside \`@coasys/ad4m-connect\`,
not from the \`@coasys/ad4m\` this repo pins. An SDK fix reaches the app only when ad4m-connect
republishes, so measure performance work against that copy, not the workspace one.

In that copy, \`getAllShacl()\` reads every shape one at a time — \`getShaclNames()\`, then \`getShacl()\`
per shape at 3 + P calls for P properties — and it rejects outright when one shape carries a
property transform a newer SDK encoded. For a question about many shapes, ask the executor
once with SPARQL, and read a shape in full only when the answer needs it: \`readShapeProperties\` and
\`getForeignShacl\` in \`perspectiveHelpers.ts\` show how.

---

### Solid + Lit Web Component Event Handling

**How the event type generator works** (\`packages/design-system/3-primitives/scripts/generate-framework-declarations.ts\`):

For Solid, two categories of event props are generated per element:
- **Native DOM events** → camelCase delegated handlers (\`onClick\`, \`onInput\`, \`onChange\`, etc.) via Solid's synthetic delegation system
- **Custom Lit events** declared in the Custom Elements Manifest → \`'on:eventname'\` direct listeners (e.g. \`'on:select'\`, \`'on:toggle'\`)

The \`on:eventname\` syntax is Solid's escape hatch for adding a direct \`addEventListener\` on the host element, bypassing delegation entirely.

**\`we-menu-item\` — always use \`on:select\`, not \`onClick\`**

\`we-menu-item\` dispatches a \`select\` CustomEvent (composed, bubbles) when clicked — this is its designed public API. The generated Solid type already includes \`'on:select'?: (event: CustomEvent) => void\`.

\`\`\`tsx
// ✅ Correct — uses designed API, already typed, works through shadow DOM + popover
<we-menu-item value={opt.value} on:select={() => handleSelect(opt)}>
  <we-text>{opt.label}</we-text>
</we-menu-item>

// ❌ Wrong — 'on:click' is not in the generated type (TypeScript error)
<we-menu-item value={opt.value} on:click={() => handleSelect(opt)}>

// ❌ Unreliable — onClick uses Solid delegation which may not reach elements
// inside shadow DOM or we-popover's browser top-layer
<we-menu-item value={opt.value} onClick={() => handleSelect(opt)}>
\`\`\`

**Why delegation fails inside \`we-popover\`**: Solid's delegated events (\`onClick\`, etc.) are registered at the Solid root element. Events from inside shadow DOM stacks or the browser's Popover API top layer may not reach the delegation root correctly due to shadow boundary retargeting. Always prefer \`on:select\` for \`we-menu-item\` — it adds a direct listener on the host element itself.

**General rule for other web component events**: if you need to listen to a native DOM event (e.g. \`click\`, \`input\`) on a \`we-\` primitive inside a deep shadow DOM context and \`onClick\`/\`onInput\` prove unreliable, use a \`ref\` callback with \`addEventListener\` directly — this never has delegation issues:
\`\`\`tsx
<we-some-element ref={(el) => el.addEventListener('click', handler)} />
\`\`\`

---

### Shadow DOM + Slots: Third-party Library Root Detection

Lit primitives (\`we-scroll-area\`, \`we-popover\`, etc.) use Shadow DOM with \`<slot>\`.
Light-DOM children are slotted through, but their \`assignedSlot\` property points into
the Shadow Root. Any library that auto-detects its document root by walking up via
\`assignedSlot\` will end up scoped to the **ShadowRoot** rather than the main document.

**Symptoms when a library is incorrectly scoped to a ShadowRoot:**
- Styles injected by the library don't apply to its own DOM elements (which live in the light DOM)
- \`document.activeElement\` checks fail because the library checks \`shadowRoot.activeElement\` instead
- Everything works only after another instance of the same library mounts outside the web component

**Known affected library: CodeMirror 6**

CM6's \`getRoot()\` follows \`assignedSlot\` into the Shadow Root. Symptoms: editor shows
only the gutter (unstyled), cursor/focus detection broken. Fix: always pass
\`root: containerRef.ownerDocument\` to the \`EditorView\` constructor. \`ownerDocument\`
skips the slot chain and always returns the main \`Document\`.

\`\`\`tsx
// ✅ Always do this when mounting a CodeMirror EditorView inside any we-* component
view = new EditorView({
  parent: containerRef,
  root: containerRef.ownerDocument,
  ...
});
\`\`\`

**General rule for other libraries**: if a third-party library accepts a \`document\`,
\`root\`, or \`container\` option and uses it for style injection or focus detection,
pass \`element.ownerDocument\` explicitly rather than letting the library auto-detect.
`;
