export type Props = Record<string, unknown>;
export type MapProp = { items: unknown; select: Props };
export type PickProp = { from: unknown; props: string[] };
export type IfProp = { condition: unknown; then: unknown; else?: unknown };
export type ConcatProp = unknown[];
export type FilterProp = { items: unknown; where: Record<string, unknown> };
export type CountProp = { items: unknown };
export type FindProp = { items: unknown; where?: Record<string, unknown>; select?: string };
export type PluralProp = { count: unknown; one: string; other: string };
export type Memo = <T>(fn: () => T) => T;
export const noMemo: Memo = (fn) => fn();
