import { readdir, readFile, stat } from 'node:fs/promises';
import { relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import { buildValidationContext, validateSemantic, validateStructure } from '@we/schema-shared';

// ── ANSI codes ─────────────────────────────────────────────────────

const red = '\x1b[31m';
const yellow = '\x1b[33m';
const green = '\x1b[32m';
const dim = '\x1b[2m';
const bold = '\x1b[1m';
const reset = '\x1b[0m';

// ── File discovery ─────────────────────────────────────────────────

async function findSchemaFiles(args: string[]): Promise<string[]> {
  // If specific files given, resolve them directly
  if (args.length > 0) {
    const files: string[] = [];
    for (const arg of args) {
      const resolved = resolve(arg);
      const s = await stat(resolved).catch(() => null);
      if (!s) {
        console.warn(`${yellow}⚠${reset} ${arg}: not found, skipping`);
        continue;
      }
      if (s.isFile() && resolved.endsWith('.schema.ts')) {
        files.push(resolved);
      } else if (s.isDirectory()) {
        files.push(...(await walkDir(resolved)));
      }
    }
    return [...new Set(files)].sort();
  }

  // Default: search from cwd recursively
  return walkDir(process.cwd());
}

async function walkDir(dir: string): Promise<string[]> {
  const files: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      // Skip node_modules, dist, .git, target
      if (['node_modules', 'dist', '.git', 'target', '.turbo'].includes(entry.name)) continue;
      files.push(...(await walkDir(fullPath)));
    } else if (entry.isFile() && entry.name.endsWith('.schema.ts')) {
      files.push(fullPath);
    }
  }
  return files;
}

// ── Schema import ──────────────────────────────────────────────────

async function importSchema(filePath: string): Promise<{ name: string; schema: unknown } | null> {
  try {
    const mod = (await import(pathToFileURL(filePath).href)) as Record<string, unknown>;

    // Find the first exported TemplateSchema or SchemaNode (named exports)
    for (const [name, value] of Object.entries(mod)) {
      if (name === 'default') continue;
      if (typeof value === 'object' && value !== null && 'type' in value) {
        return { name, schema: value };
      }
    }

    console.warn(`${yellow}⚠${reset} ${relative(process.cwd(), filePath)}: no schema export found`);
    return null;
  } catch (err) {
    console.error(`${red}✗${reset} ${relative(process.cwd(), filePath)}: import failed — ${(err as Error).message}`);
    return null;
  }
}

// ── Main ───────────────────────────────────────────────────────────

const args = process.argv.slice(2);

// Find files
const files = await findSchemaFiles(args);
if (files.length === 0) {
  console.log(`${dim}No .schema.ts files found.${reset}`);
  process.exit(0);
}

// Build validation context from pre-built JSON (generated by @we/ai-context build)
const contextJsonPath = resolve(process.cwd(), 'packages', 'ai-context', 'context.json');
let contextJson: string;
try {
  contextJson = await readFile(contextJsonPath, 'utf-8');
} catch {
  console.error(`${red}✗${reset} Cannot find context.json at ${contextJsonPath}`);
  console.error(`  Run "pnpm --filter @we/ai-context generate-context" first.`);
  process.exit(1);
}
const contextData = JSON.parse(contextJson);
const validationContext = buildValidationContext(contextData);

// Validate each file
let totalErrors = 0;
let totalWarnings = 0;
let filesWithIssues = 0;

for (const filePath of files) {
  const result = await importSchema(filePath);
  if (!result) continue;

  const relPath = relative(process.cwd(), filePath);

  // Run structural validation
  const structural = validateStructure(result.schema);

  // Run semantic validation (even if structural fails, to show all issues)
  const semantic = validateSemantic(result.schema, validationContext);

  const allErrors = [...structural.errors, ...semantic.errors];
  if (allErrors.length === 0) {
    console.log(`${green}✓${reset} ${dim}${relPath}${reset}`);
    continue;
  }

  filesWithIssues++;

  const errors = allErrors.filter((e) => e.severity === 'error');
  const warnings = allErrors.filter((e) => e.severity === 'warning');
  totalErrors += errors.length;
  totalWarnings += warnings.length;

  const counts = [
    errors.length > 0 ? `${red}${errors.length} error${errors.length > 1 ? 's' : ''}${reset}` : '',
    warnings.length > 0 ? `${yellow}${warnings.length} warning${warnings.length > 1 ? 's' : ''}${reset}` : '',
  ]
    .filter(Boolean)
    .join(', ');

  console.log(`\n${bold}${relPath}${reset} ${dim}(${result.name})${reset} — ${counts}`);

  for (const err of allErrors) {
    const icon = err.severity === 'error' ? `${red}✗${reset}` : `${yellow}⚠${reset}`;
    const pathStr = err.path ? `${dim}${err.path}${reset} ` : '';
    console.log(`  ${icon} ${pathStr}${err.message}`);
  }
}

// Summary
console.log('');
if (totalErrors === 0 && totalWarnings === 0) {
  console.log(`${green}✓ ${files.length} schema${files.length > 1 ? 's' : ''} validated — no issues found${reset}`);
} else {
  const parts = [`${files.length} schema${files.length > 1 ? 's' : ''} checked`, `${filesWithIssues} with issues`];
  if (totalErrors > 0) parts.push(`${red}${totalErrors} error${totalErrors > 1 ? 's' : ''}${reset}`);
  if (totalWarnings > 0) parts.push(`${yellow}${totalWarnings} warning${totalWarnings > 1 ? 's' : ''}${reset}`);
  console.log(parts.join(', '));
}

// Exit non-zero on errors (warnings are ok)
if (totalErrors > 0) {
  process.exit(1);
}
