/**
 * Auto-generated Seed Server Setup
 * 
 * This file is generated by scripts/generate-seed-config.js
 * Do not edit manually - changes will be overwritten!
 * 
 * Sets up Express servers for each app defined in we-seed.json
 */

import express from 'express';
import { app } from 'electron';
import { existsSync } from 'fs';
import { join } from 'path';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Setup Express servers for all apps from seed configuration
 * 
 * In development: Serves from dist paths in workspace
 * In production: Serves from bundled resources
 * 
 * @returns {Array} Array of Express server instances
 */
export function setupSeedServers() {
  const servers = [];

  // Flux (flux)
  const fluxDir = app.isPackaged
    ? join(process.resourcesPath, 'flux')
    : join(__dirname, '..', '..', '..', '../flux/app/dist');

  if (existsSync(fluxDir)) {
    console.log('📦 Starting Flux server on http://localhost:8080');
    console.log('   Serving from:', fluxDir);

    const fluxApp = express();
    fluxApp.use(express.static(fluxDir, {
      setHeaders: (res) => {
        res.removeHeader('X-Frame-Options');
        res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
      },
    }));
    
    // Fallback to index.html for SPA routing
    fluxApp.use((req, res) => {
      res.sendFile(join(fluxDir, 'index.html'));
    });
    
    const fluxServer = fluxApp.listen(8080, () => {
      console.log('   ✓ Flux server listening on port 8080');
    });
    
    servers.push(fluxServer);
  } else {
    console.warn('⚠️  Flux directory not found at:', fluxDir);
  }

  // Playground (playground)
  const playgroundDir = app.isPackaged
    ? join(process.resourcesPath, 'playground')
    : join(__dirname, '..', '..', '..', './apps/playgrounds/react/demo/dist');

  if (existsSync(playgroundDir)) {
    console.log('📦 Starting Playground server on http://localhost:8081');
    console.log('   Serving from:', playgroundDir);

    const playgroundApp = express();
    playgroundApp.use(express.static(playgroundDir, {
      setHeaders: (res) => {
        res.removeHeader('X-Frame-Options');
        res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
      },
    }));
    
    // Fallback to index.html for SPA routing
    playgroundApp.use((req, res) => {
      res.sendFile(join(playgroundDir, 'index.html'));
    });
    
    const playgroundServer = playgroundApp.listen(8081, () => {
      console.log('   ✓ Playground server listening on port 8081');
    });
    
    servers.push(playgroundServer);
  } else {
    console.warn('⚠️  Playground directory not found at:', playgroundDir);
  }

  return servers;
}
