/**
 * Auto-generated Seed Server Setup
 *
 * This file is generated by scripts/generate-seed-config.js
 * Do not edit manually - changes will be overwritten!
 *
 * Empty setup - no embedded apps in native WE mode
 */

/**
 * Setup Express servers for all apps from seed configuration
 *
 * @returns {Array} Empty array (no embedded apps)
 */
export function setupSeedServers() {
  // No embedded apps in native WE mode
  return [];
}
